export const tracks = [
    // Featured New Tracks
    { title: "Neon Bot Odyssey", url: "/Neon Bot Odyssey.mp3", genre: "Cyberpunk" },
    { title: "Kaguya Glitch", url: "/Kaguya Glitch (#spaceport).mp3", genre: "Cyberpunk" },
    { title: "Bittersweet Gravity", url: "/Bittersweet Gravity.mp3", genre: "Ethereal" },
    { title: "Moth Among the Stars", url: "/Moth Among the Stars (Live).mp3", genre: "Ethereal" },
    { title: "Haunted", url: "/Haunted.mp3", genre: "Dark" },
    { title: "Visions of Zombie Robby", url: "/95 - Visions of Zombie Robby.mp3", genre: "Dark" },
    { title: "Drop it low", url: "/Drop it low.mp3", genre: "Energetic" },
    { title: "Gitgologic", url: "/Gitgologic.mp3", genre: "Energetic" },
    
    // More New Tracks
    { title: "Always", url: "/Always.mp3", genre: "Ethereal" },
    { title: "April's Gone", url: "/April's Gone.mp3", genre: "Ethereal" },
    { title: "Calibrate Your Peace", url: "/Calibrate Your Peace by BB ft ICHI.mp3", genre: "Ethereal" },
    { title: "Carnivore or Herbivore", url: "/Carnivore or Herbivore.mp3", genre: "Energetic" },
    { title: "Closer To You", url: "/Closer To You.mp3", genre: "Cyberpunk" },
    { title: "Delapidated", url: "/Delapidated (Cover).mp3", genre: "Dark" },
    { title: "Elixir", url: "/Elixir.mp3", genre: "Cyberpunk" },
    { title: "Endless Pandemic", url: "/Endless Pandemic (Sad).mp3", genre: "Dark" },
    { title: "Everything’s Fine", url: "/Everything’s Fine.mp3", genre: "Energetic" },
    { title: "Join Me In The Ring", url: "/JOIN ME IN THE RING OF PRIDE.mp3", genre: "Energetic" },
    { title: "Liberty or Cruelty", url: "/𝕃𝕚𝕓𝕖𝕣𝕥𝕪 𝕠𝕣 ℂ𝕣𝕦𝕖𝕝𝕥𝕪..._.mp3", genre: "Dark" },
    { title: "Ma flamme, ma malédiction", url: "/🇫🇷 Ma flamme, ma malédiction.mp3", genre: "Ethereal" },
    { title: "Memory", url: "/Memory.mp3", genre: "Ethereal" },
    { title: "Miles and Memories", url: "/Miles and Memories.mp3", genre: "Ethereal" },
    { title: "Mortal", url: "/Mortal (NOW on Spotify, Apple Music, Youtube-Music etc.).mp3", genre: "Energetic" },
    { title: "My Sleep Paralysis Friend", url: "/My sleep paralysis friend.mp3", genre: "Dark" },
    { title: "Paillettes / Glitters", url: "/Paillettes _ Glitters.mp3", genre: "Ethereal" },
    { title: "Root & Rise", url: "/Root & Rise.mp3", genre: "Ethereal" },
    { title: "Shadows in my chest", url: "/Shadows in my chest.mp3", genre: "Dark" },
    { title: "So This Is Love", url: "/so this is love.mp3", genre: "Ethereal" },
    { title: "The Transitive Shuffle", url: "/The Transitive Shuffle.mp3", genre: "Cyberpunk" },
    { title: "Witch", url: "/Ꮤ𐌉𐌕𐌂𐋅.mp3", genre: "Dark" },

    // Classics
    { title: "PhonkPhonics", url: "/PhonkPhonics.mp3", genre: "Phonk" },
    { title: "Playing with Fire v5", url: "/Playing with Fire v5 (2000s).mp3", genre: "2000s" },
    { title: "Poly Rhytms", url: "/Poly Rhytms.mp3", genre: "Poly" },
    { title: "Rave Revolution", url: "/Rave Revolution(v5).mp3", genre: "Rave" },
    { title: "Reggae On Repeat", url: "/Reggae On Repeat.mp3", genre: "Reggae" },
    { title: "Rhytmic Delight", url: "/Rhytmic Delight.mp3", genre: "Rhythmic" },
    { title: "Skubadiboopboop", url: "/Skubadiboopboop.mp3", genre: "Jazz Scat" },
    { title: "Slide Right", url: "/Slide Right.mp3", genre: "Electronic" },
    { title: "Suno V5 is Here (1)", url: "/Suno V5 is Here (1).mp3", genre: "Experimental" },
    { title: "Suno V5 is Here", url: "/Suno V5 is Here.mp3", genre: "Experimental" },
    { title: "The Edge of Tomorrow", url: "/The Edge of Tomorrow(v5).mp3", genre: "Cinematic" },
    { title: "Welcome Aboard", url: "/Welcome Aboard the Future Funk Expressway Girl.mp3", genre: "Future Funk" }
];
